kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Sales-Api
      - containerPort: 3000
        hostPort: 3000
      # Sales-Api debug
      - containerPort: 3010
        hostPort: 3010
      # Metrics
      - containerPort: 4000
        hostPort: 4000
      # Metrics debug
      - containerPort: 4010
        hostPort: 4010
      # Auth
      - containerPort: 6000
        hostPort: 6000
      # Auth debug
      - containerPort: 6010
        hostPort: 6010
      # Postgres
      - containerPort: 5432
        hostPort: 5432