apiVersion: v1
kind: Service
metadata:
  name: harvester-service
  namespace: harvester-system

spec:
  type: ClusterIP

  ports:
    - name: harvester
      port: 3000
      targetPort: harvester
    - name: harvester-debug
      port: 3010
      targetPort: harvester-debug