package migrate

// ResourceTypes contains all valid resource types from Star Wars Galaxies
var ResourceTypes = []string{
	"Agrinium",
	"Aluminum",
	"Alantium",
	"Carbonate Ore",
	"Ardanium",
	"Siliclastic Ore",
	"Axidite",
	"Iron",
	"Bal'ta'ran Crystal",
	"Amorphous Gemstone",
	"Baradium",
	"Barthierium",
	"Bene",
	"Extrusive Ore",
	"Berubium",
	"Intrusive Ore",
	"Beyrllius",
	"Copper",
	"Bilal",
	"Inert Gas",
	"Blended Wood",
	"Bospridium",
	"Bronzium",
	"Byrothsis",
	"Crystalline Gemstone",
	"Cagunese",
	"Calabite",
	"Carbonite",
	"Steel",
	"Chanlon",
	"Chemical Compound",
	"Chromite",
	"Chromium",
	"Chronamite",
	"Class 1 Liquid Petro Fuel",
	"Class 1 Radioactive",
	"Class 1 Solid Petro Fuel",
	"Class 2 Liquid Petro Fuel",
	"Class 2 Radioactive",
	"Class 2 Solid Petro Fuel",
	"Class 3 Liquid Petro Fuel",
	"Class 3 Radioactive",
	"Class 3 Solid Petro Fuel",
	"Class 4 Liquid Petro Fuel",
	"Class 4 Radioactive",
	"Class 4 Solid Petro Fuel",
	"Class 5 Liquid Petro Fuel",
	"Class 5 Radioactive",
	"Class 5 Solid Petro Fuel",
	"Class 6 Liquid Petro Fuel",
	"Class 6 Radioactive",
	"Class 6 Solid Petro Fuel",
	"Class 7 Liquid Petro Fuel",
	"Class 7 Radioactive",
	"Class 7 Solid Petro Fuel",
	"Codoan",
	"Colat",
	"Combined Radioactive Isotopes",
	"Conductive Borcarbitic",
	"Corellian Animal Bones",
	"Corellian Avian Bones",
	"Corellian Avian Meat",
	"Corellian Berry Fruit",
	"Corellian Bristley Hide",
	"Corellian Carnivore Meat",
	"Corellian Conifer Wood",
	"Corellian Deciduous Wood",
	"Corellian Domesticated Corn",
	"Corellian Domesticated Meat",
	"Corellian Domesticated Milk",
	"Corellian Domesticated Oats",
	"Corellian Domesticated Rice",
	"Corellian Domesticated Wheat",
	"Corellian Egg Meat",
	"Corellian Evergreen Wood",
	"Corellian Fiberplast",
	"Corellian Fish Meat",
	"Corellian Flower Fruit",
	"Corellian Fruit",
	"Corellian Geothermal Renewable Energy",
	"Corellian Herbivore Meat",
	"Corellian Horn",
	"Corellian Hydron-3 Renewable Energy",
	"Corellian Insect Meat",
	"Corellian Leathery Hide",
	"Corellian Mollusk Meat",
	"Corellian Reptillian Meat",
	"Corellian Scaley Hide",
	"Corellian Solar Renewable Energy",
	"Corellian Tidal Renewable Energy",
	"Corellian Vegetable Beans",
	"Corellian Vegetable Fungus",
	"Corellian Vegetable Greens",
	"Corellian Vegetable Tubers",
	"Corellian Water Vapor",
	"Corellian Wild Corn",
	"Corellian Wild Meat",
	"Corellian Wild Milk",
	"Corellian Wild Oats",
	"Corellian Wild Rice",
	"Corellian Wild Wheat",
	"Corellian Wind Renewable Energy",
	"Corellian Wooly Hide",
	"Corintium",
	"Corthel",
	"Cortosis",
	"Crism",
	"Crystallized Bicorbantium",
	"Cubirian",
	"Culsion",
	"Dantooine Animal Bones",
	"Dantooine Avian Bones",
	"Dantooine Avian Meat",
	"Dantooine Berry Fruit",
	"Dantooine Bristley Hide",
	"Dantooine Carnivore Meat",
	"Dantooine Conifer Wood",
	"Dantooine Crustacean Meat",
	"Dantooine Deciduous Wood",
	"Dantooine Domesticated Corn",
	"Dantooine Domesticated Meat",
	"Dantooine Domesticated Milk",
	"Dantooine Domesticated Oats",
	"Dantooine Domesticated Rice",
	"Dantooine Domesticated Wheat",
	"Dantooine Egg Meat",
	"Dantooine Evergreen Wood",
	"Dantooine Fiberplast",
	"Dantooine Fish Meat",
	"Dantooine Flower Fruit",
	"Dantooine Fruit",
	"Dantooine Geothermal Renewable Energy",
	"Dantooine Herbivore Meat",
	"Dantooine Horn",
	"Dantooine Hydron-3 Renewable Energy",
	"Dantooine Insect Meat",
	"Dantooine Leathery Hide",
	"Dantooine Mollusk Meat",
	"Dantooine Reptillian Meat",
	"Dantooine Scaley Hide",
	"Dantooine Solar Renewable Energy",
	"Dantooine Tidal Renewable Energy",
	"Dantooine Vegetable Beans",
	"Dantooine Vegetable Fungus",
	"Dantooine Vegetable Greens",
	"Dantooine Vegetable Tubers",
	"Dantooine Water Vapor",
	"Dantooine Wild Corn",
	"Dantooine Wild Meat",
	"Dantooine Wild Milk",
	"Dantooine Wild Oats",
	"Dantooine Wild Rice",
	"Dantooine Wild Wheat",
	"Dantooine Wind Renewable Energy",
	"Dantooine Wooly Hide",
	"Dathomirian Animal Bones",
	"Dathomirian Avian Bones",
	"Dathomirian Avian Meat",
	"Dathomirian Berry Fruit",
	"Dathomirian Bristley Hide",
	"Dathomirian Carnivore Meat",
	"Dathomirian Conifer Wood",
	"Dathomirian Crustacean Meat",
	"Dathomirian Deciduous Wood",
	"Dathomirian Domesticated Corn",
	"Dathomirian Domesticated Meat",
	"Dathomirian Domesticated Milk",
	"Dathomirian Domesticated Oats",
	"Dathomirian Domesticated Rice",
	"Dathomirian Domesticated Wheat",
	"Dathomirian Egg Meat",
	"Dathomirian Evergreen Wood",
	"Dathomirian Fiberplast",
	"Dathomirian Fish Meat",
	"Dathomirian Flower Fruit",
	"Dathomirian Fruit",
	"Dathomirian Geothermal Renewable Energy",
	"Dathomirian Herbivore Meat",
	"Dathomirian Horn",
	"Dathomirian Hydron-3 Renewable Energy",
	"Dathomirian Insect Meat",
	"Dathomirian Leathery Hide",
	"Dathomirian Mollusk Meat",
	"Dathomirian Reptillian Meat",
	"Dathomirian Scaley Hide",
	"Dathomirian Solar Renewable Energy",
	"Dathomirian Tidal Renewable Energy",
	"Dathomirian Vegetable Beans",
	"Dathomirian Vegetable Fungus",
	"Dathomirian Vegetable Greens",
	"Dathomirian Vegetable Tubers",
	"Dathomirian Water Vapor",
	"Dathomirian Wild Corn",
	"Dathomirian Wild Meat",
	"Dathomirian Wild Milk",
	"Dathomirian Wild Oats",
	"Dathomirian Wild Rice",
	"Dathomirian Wild Wheat",
	"Dathomirian Wind Renewable Energy",
	"Dathomirian Wooly Hide",
	"Degraded Solid Petrochem Fuel",
	"Derillium",
	"Desh",
	"Diatium",
	"Dioxis",
	"Ditanium",
	"Dolovite",
	"Doonium",
	"Duralloy",
	"Duralumin",
	"Duranium",
	"Dylinium",
	"Eleton",
	"Endorian Animal Bones",
	"Endorian Avian Bones",
	"Endorian Avian Meat",
	"Endorian Berry Fruit",
	"Endorian Bristley Hide",
	"Endorian Carnivore Meat",
	"Endorian Conifer Wood",
	"Endorian Crustacean Meat",
	"Endorian Deciduous Wood",
	"Endorian Domesticated Corn",
	"Endorian Domesticated Meat",
	"Endorian Domesticated Milk",
	"Endorian Domesticated Oats",
	"Endorian Domesticated Rice",
	"Endorian Domesticated Wheat",
	"Endorian Egg Meat",
	"Endorian Evergreen Wood",
	"Endorian Fiberplast",
	"Endorian Fish Meat",
	"Endorian Flower Fruit",
	"Endorian Fruit",
	"Endorian Geothermal Renewable Energy",
	"Endorian Herbivore Meat",
	"Endorian Horn",
	"Endorian Hydron-3 Renewable Energy",
	"Endorian Insect Meat",
	"Endorian Leathery Hide",
	"Endorian Mollusk Meat",
	"Endorian Reptillian Meat",
	"Endorian Scaley Hide",
	"Endorian Solar Renewable Energy",
	"Endorian Tidal Renewable Energy",
	"Endorian Vegetable Beans",
	"Endorian Vegetable Fungus",
	"Endorian Vegetable Greens",
	"Endorian Vegetable Tubers",
	"Endorian Water Vapor",
	"Endorian Wild Corn",
	"Endorian Wild Meat",
	"Endorian Wild Milk",
	"Endorian Wild Oats",
	"Endorian Wild Rice",
	"Endorian Wild Wheat",
	"Endorian Wind Renewable Energy",
	"Endorian Wooly Hide",
	"Fermionic",
	"Frasium",
	"Galatite",
	"Gallinorian Rainbow Gem",
	"Galvanicyn",
	"Gravitonic",
	"Green Diamond",
	"Ground Bones",
	"Ground Horn",
	"Hardened Arveshium",
	"Hemalite",
	"High Grade Polymetric Radioactive",
	"Hollinium",
	"Homogenized Milk",
	"Hurlothrombic",
	"Hydron-3",
	"Ilimium",
	"Ionite",
	"Irolunn",
	"Kalonterium",
	"Kammris",
	"Katrium",
	"Kaylon",
	"Kelsh",
	"Kerol Fire-Gem",
	"Keschel",
	"Kiirium",
	"Korfaise",
	"Laboi Mineral Crystal",
	"Lidium",
	"Link-Steel",
	"Lokian Animal Bones",
	"Lokian Avian Bones",
	"Lokian Avian Meat",
	"Lokian Berry Fruit",
	"Lokian Bristley Hide",
	"Lokian Carnivore Meat",
	"Lokian Conifer Wood",
	"Lokian Crustacean Meat",
	"Lokian Deciduous Wood",
	"Lokian Domesticated Corn",
	"Lokian Domesticated Meat",
	"Lokian Domesticated Milk",
	"Lokian Domesticated Oats",
	"Lokian Domesticated Rice",
	"Lokian Domesticated Wheat",
	"Lokian Egg Meat",
	"Lokian Evergreen Wood",
	"Lokian Fiberplast",
	"Lokian Fish Meat",
	"Lokian Flower Fruit",
	"Lokian Fruit",
	"Lokian Geothermal Renewable Energy",
	"Lokian Herbivore Meat",
	"Lokian Horn",
	"Lokian Hydron-3 Renewable Energy",
	"Lokian Insect Meat",
	"Lokian Leathery Hide",
	"Lokian Mollusk Meat",
	"Lokian Reptillian Meat",
	"Lokian Scaley Hide",
	"Lokian Solar Renewable Energy",
	"Lokian Tidal Renewable Energy",
	"Lokian Vegetable Beans",
	"Lokian Vegetable Fungus",
	"Lokian Vegetable Greens",
	"Lokian Vegetable Tubers",
	"Lokian Water Vapor",
	"Lokian Wild Corn",
	"Lokian Wild Meat",
	"Lokian Wild Milk",
	"Lokian Wild Oats",
	"Lokian Wild Rice",
	"Lokian Wild Wheat",
	"Lokian Wind Renewable Energy",
	"Lokian Wooly Hide",
	"Lommite",
	"Low Grade Ore (igneous)",
	"Low Grade Ore (sedimentary)",
	"Low Grade Ore (siliclastic)",
	"Low Quality Gemstones",
	"Lubricating Oil",
	"Maganite",
	"Malab",
	"Malium",
	"Maranium",
	"Methanagen",
	"Methane",
	"Mirth",
	"Mixed Fruits",
	"Mixed Inert Gas",
	"Mixed Reactive Gas",
	"Mixed Vegetables",
	"Mythra",
	"Nabooian Animal Bones",
	"Nabooian Avian Bones",
	"Nabooian Avian Meat",
	"Nabooian Berry Fruit",
	"Nabooian Bristley Hide",
	"Nabooian Carnivore Meat",
	"Nabooian Conifer Wood",
	"Nabooian Crustacean Meat",
	"Nabooian Deciduous Wood",
	"Nabooian Domesticated Corn",
	"Nabooian Domesticated Meat",
	"Nabooian Domesticated Milk",
	"Nabooian Domesticated Oats",
	"Nabooian Domesticated Rice",
	"Nabooian Domesticated Wheat",
	"Nabooian Egg Meat",
	"Nabooian Evergreen Wood",
	"Nabooian Fiberplast",
	"Nabooian Fish Meat",
	"Nabooian Flower Fruit",
	"Nabooian Fruit",
	"Nabooian Geothermal Renewable Energy",
	"Nabooian Herbivore Meat",
	"Nabooian Horn",
	"Nabooian Hydron-3 Renewable Energy",
	"Nabooian Insect Meat",
	"Nabooian Leathery Hide",
	"Nabooian Mollusk Meat",
	"Nabooian Reptillian Meat",
	"Nabooian Scaley Hide",
	"Nabooian Solar Renewable Energy",
	"Nabooian Tidal Renewable Energy",
	"Nabooian Vegetable Beans",
	"Nabooian Vegetable Fungus",
	"Nabooian Vegetable Greens",
	"Nabooian Vegetable Tubers",
	"Nabooian Water Vapor",
	"Nabooian Wild Corn",
	"Nabooian Wild Meat",
	"Nabooian Wild Milk",
	"Nabooian Wild Oats",
	"Nabooian Wild Rice",
	"Nabooian Wild Wheat",
	"Nabooian Wind Renewable Energy",
	"Nabooian Wooly Hide",
	"Neutronium",
	"Obah",
	"Oridium",
	"Orveth",
	"Ostrine",
	"Perovskitic",
	"Pholokite",
	"Phrik",
	"Platinite",
	"Plexite",
	"Plumbum",
	"Polonium",
	"Polymer",
	"Polysteel",
	"Processed Cereal",
	"Processed Meat",
	"Processed Seafood",
	"Quadranium",
	"Quadrenium",
	"Regvis",
	"Rethin",
	"Rhodium",
	"Robindun",
	"Rori Animal Bones",
	"Rori Avian Bones",
	"Rori Avian Meat",
	"Rori Berry Fruit",
	"Rori Bristley Hide",
	"Rori Carnivore Meat",
	"Rori Conifer Wood",
	"Rori Crustacean Meat",
	"Rori Deciduous Wood",
	"Rori Domesticated Corn",
	"Rori Domesticated Meat",
	"Rori Domesticated Milk",
	"Rori Domesticated Oats",
	"Rori Domesticated Rice",
	"Rori Domesticated Wheat",
	"Rori Egg Meat",
	"Rori Evergreen Wood",
	"Rori Fiberplast",
	"Rori Fish Meat",
	"Rori Flower Fruit",
	"Rori Fruit",
	"Rori Geothermal Renewable Energy",
	"Rori Herbivore Meat",
	"Rori Horn",
	"Rori Hydron-3 Renewable Energy",
	"Rori Insect Meat",
	"Rori Leathery Hide",
	"Rori Mollusk Meat",
	"Rori Reptillian Meat",
	"Rori Scaley Hide",
	"Rori Solar Renewable Energy",
	"Rori Tidal Renewable Energy",
	"Rori Vegetable Beans",
	"Rori Vegetable Fungus",
	"Rori Vegetable Greens",
	"Rori Vegetable Tubers",
	"Rori Water Vapor",
	"Rori Wild Corn",
	"Rori Wild Meat",
	"Rori Wild Milk",
	"Rori Wild Oats",
	"Rori Wild Rice",
	"Rori Wild Wheat",
	"Rori Wind Renewable Energy",
	"Rori Wooly Hide",
	"Rudic",
	"Ryll",
	"Rylon",
	"Seafah Jewel",
	"Sedrellium",
	"Sig",
	"Skevon",
	"Smelted Aluminum",
	"Smelted Copper",
	"Smelted Ferrous Metal",
	"Smelted Iron",
	"Smelted Non-Ferrous Metal",
	"Smelted Steel",
	"Sormahil Fire Gem",
	"Stygium",
	"Synthesized Hides",
	"Talusian Animal Bones",
	"Talusian Avian Bones",
	"Talusian Avian Meat",
	"Talusian Berry Fruit",
	"Talusian Bristley Hide",
	"Talusian Carnivore Meat",
	"Talusian Conifer Wood",
	"Talusian Crustacean Meat",
	"Talusian Deciduous Wood",
	"Talusian Domesticated Corn",
	"Talusian Domesticated Meat",
	"Talusian Domesticated Milk",
	"Talusian Domesticated Oats",
	"Talusian Domesticated Rice",
	"Talusian Domesticated Wheat",
	"Talusian Egg Meat",
	"Talusian Evergreen Wood",
	"Talusian Fiberplast",
	"Talusian Fish Meat",
	"Talusian Flower Fruit",
	"Talusian Fruit",
	"Talusian Geothermal Renewable Energy",
	"Talusian Herbivore Meat",
	"Talusian Horn",
	"Talusian Hydron-3 Renewable Energy",
	"Talusian Insect Meat",
	"Talusian Leathery Hide",
	"Talusian Mollusk Meat",
	"Talusian Reptillian Meat",
	"Talusian Scaley Hide",
	"Talusian Solar Renewable Energy",
	"Talusian Tidal Renewable Energy",
	"Talusian Vegetable Beans",
	"Talusian Vegetable Fungus",
	"Talusian Vegetable Greens",
	"Talusian Vegetable Tubers",
	"Talusian Water Vapor",
	"Talusian Wild Corn",
	"Talusian Wild Meat",
	"Talusian Wild Milk",
	"Talusian Wild Oats",
	"Talusian Wild Rice",
	"Talusian Wild Wheat",
	"Talusian Wind Renewable Energy",
	"Talusian Wooly Hide",
	"Tatooinian Animal Bones",
	"Tatooinian Avian Bones",
	"Tatooinian Avian Meat",
	"Tatooinian Berry Fruit",
	"Tatooinian Bristley Hide",
	"Tatooinian Carnivore Meat",
	"Tatooinian Conifer Wood",
	"Tatooinian Crustacean Meat",
	"Tatooinian Deciduous Wood",
	"Tatooinian Domesticated Corn",
	"Tatooinian Domesticated Meat",
	"Tatooinian Domesticated Milk",
	"Tatooinian Domesticated Oats",
	"Tatooinian Domesticated Rice",
	"Tatooinian Domesticated Wheat",
	"Tatooinian Egg Meat",
	"Tatooinian Evergreen Wood",
	"Tatooinian Fiberplast",
	"Tatooinian Fish Meat",
	"Tatooinian Flower Fruit",
	"Tatooinian Fruit",
	"Tatooinian Geothermal Renewable Energy",
	"Tatooinian Herbivore Meat",
	"Tatooinian Horn",
	"Tatooinian Hydron-3 Renewable Energy",
	"Tatooinian Insect Meat",
	"Tatooinian Leathery Hide",
	"Tatooinian Mollusk Meat",
	"Tatooinian Reptillian Meat",
	"Tatooinian Scaley Hide",
	"Tatooinian Solar Renewable Energy",
	"Tatooinian Tidal Renewable Energy",
	"Tatooinian Vegetable Beans",
	"Tatooinian Vegetable Fungus",
	"Tatooinian Vegetable Greens",
	"Tatooinian Vegetable Tubers",
	"Tatooinian Water Vapor",
	"Tatooinian Wild Corn",
	"Tatooinian Wild Meat",
	"Tatooinian Wild Milk",
	"Tatooinian Wild Oats",
	"Tatooinian Wild Rice",
	"Tatooinian Wild Wheat",
	"Tatooinian Wind Renewable Energy",
	"Tatooinian Wooly Hide",
	"Tertian",
	"Thallium",
	"Thoranium",
	"Titanium",
	"Tolium",
	"Unknown Ferrous Metal",
	"Unknown Gem Type",
	"Unknown Igneous Ore",
	"Unknown Inert Gas",
	"Unknown Liquid Petrochem Fuel",
	"Unknown Non-Ferrous Metal",
	"Unknown Radioactive",
	"Unknown Reactive Gas",
	"Unknown Sedimentary Ore",
	"Unknown Solid Petrochem Fuel",
	"Unstable Organometallic",
	"Varium",
	"Vendusii Crystal",
	"Vertex",
	"Vintrium",
	"Water Solution",
	"Weak Geothermal Renewable Energy",
	"Weak Hydron-3 Renewable Energy",
	"Weak Solar Renewable Energy",
	"Weak Tidal Renewable Energy",
	"Weak Wind Renewable Energy",
	"Yavinian Animal Bones",
	"Yavinian Avian Bones",
	"Yavinian Avian Meat",
	"Yavinian Berry Fruit",
	"Yavinian Bristley Hide",
	"Yavinian Carnivore Meat",
	"Yavinian Conifer Wood",
	"Yavinian Crustacean Meat",
	"Yavinian Deciduous Wood",
	"Yavinian Domesticated Corn",
	"Yavinian Domesticated Meat",
	"Yavinian Domesticated Milk",
	"Yavinian Domesticated Oats",
	"Yavinian Domesticated Rice",
	"Yavinian Domesticated Wheat",
	"Yavinian Egg Meat",
	"Yavinian Evergreen Wood",
	"Yavinian Fiberplast",
	"Yavinian Fish Meat",
	"Yavinian Flower Fruit",
	"Yavinian Fruit",
	"Yavinian Geothermal Renewable Energy",
	"Yavinian Herbivore Meat",
	"Yavinian Horn",
	"Yavinian Hydron-3 Renewable Energy",
	"Yavinian Insect Meat",
	"Yavinian Leathery Hide",
	"Yavinian Mollusk Meat",
	"Yavinian Reptillian Meat",
	"Yavinian Scaley Hide",
	"Yavinian Solar Renewable Energy",
	"Yavinian Tidal Renewable Energy",
	"Yavinian Vegetable Beans",
	"Yavinian Vegetable Fungus",
	"Yavinian Vegetable Greens",
	"Yavinian Vegetable Tubers",
	"Yavinian Water Vapor",
	"Yavinian Wild Corn",
	"Yavinian Wild Meat",
	"Yavinian Wild Milk",
	"Yavinian Wild Oats",
	"Yavinian Wild Rice",
	"Yavinian Wild Wheat",
	"Yavinian Wind Renewable Energy",
	"Yavinian Wooly Hide",
	"Zinsiam",
}
